version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/client/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/openapi/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/server/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/client/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
