openapi: 3.0.3
info:
  title: @project.description@
  version: @project.version@
servers:
  - url: http://localhost:9081/api/v1
    description: Development
paths:
  /status:
    $ref: "paths/status.yml"
  /metaModels:
    $ref: "paths/metaModels.yml"
  /projectTypes/{metaModelId}:
    $ref: "paths/projectTypes.yml"
  /projectTypeVariants/{projectTypeId}:
    $ref: "paths/projectTypeVariants.yml"
  /projectFeatures:
    $ref: "paths/projectFeatures.yml"
  /menuEntries:
    $ref: "paths/menuEntry.yml"
  /page/{pageId}:
    $ref: "paths/page.yml"


