###
POST http://localhost:9081/api/v1/product
Content-Type: application/json

{
  "productName": "SHIELD Protocol",
  "responsible": "SHIELD Initiative",
  "projectName": "Avengers",
  "participants": [
    "Nick Fury",
    "Black Widow"
  ],
  "chapters": [
    {
      "title": "Erstes Kapitel",
      "text": "Hier könnte ihre Werbung stehen..."
    },
    {
      "title": "Zweites Kapitel",
      "text": "Hier steht nur sinnloser Blindtext. Hier steht nur sinnloser Blindtext. Hier steht nur sinnloser Blindtext. Hier steht nur sinnloser Blindtext. Hier steht nur sinnloser Blindtext. Hier steht nur sinnloser Blindtext."
    }
  ]
}
