openapi: 3.0.3
info:
  title: projektassistent-openapi
  version: 0.0.2
servers:
  - url: http://localhost:9081/api/v1
    description: Development
paths:
  /status:
    $ref: "paths/status.yml"
  /modelVariants:
    $ref: "paths/modelVariants.yml"
  /projectTypes/{modellVariantId}:
    $ref: "paths/projectTypes.yml"
  /projectFeatures/{projectTypeVariantId}:
    $ref: "paths/projectFeatures.yml"
  /menuEntries:
    $ref: "paths/menuEntry.yml"
  /page/{pageId}:
    $ref: "paths/page.yml"
