# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub CI - Code-Checks

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Code-Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 14.x
          registry-url: "https://npm.pkg.github.com"
          scope: "@dipa-projekt"
      - name: Check via NPM
        run: |
          npm ci
          npm run format
          npm run lint:eslint
          npm run coverage
          npm run build
        working-directory: client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_HUB_PACKAGES_ACCESS_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check via MAVEN
        run: mvn clean install -s .mvn/settings.xml
        env:
          GIT_HUB_USERNAME: ${{ secrets.GIT_HUB_USERNAME }}
          GIT_HUB_PACKAGES_ACCESS_TOKEN: ${{ secrets.GIT_HUB_PACKAGES_ACCESS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GIT_HUB_PACKAGES_ACCESS_TOKEN }}
