# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub CI - Code-Checks

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Code-Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
          registry-url: "https://npm.pkg.github.com"
          scope: "@dipa-projekt"
      # - name: Configure NPM
      #   run: |
      #     # npm config set @dipa-projekt:registry https://npm.pkg.github.com
      #     npm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.GIT_HUB_PACKAGES_ACCESS_TOKEN }}
      # - name: Install dependencies
      #   run: npm ci
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GIT_HUB_PACKAGES_ACCESS_TOKEN }}
      #   working-directory: client
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check
        run: |
          mvn clean install -pl client,server
        env:
          GIT_HUB_USERNAME: ${{ secrets.GIT_HUB_USERNAME }}
          GIT_HUB_PACKAGES_ACCESS_TOKEN: ${{ secrets.GIT_HUB_PACKAGES_ACCESS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GIT_HUB_PACKAGES_ACCESS_TOKEN }}
